# Generated by Django 3.2.16 on 2022-11-20 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='option',
            field=models.IntegerField(verbose_name='操作'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(verbose_name='状态'),
        ),
    ]
