# Generated by Django 3.2.16 on 2022-11-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_task_task_name2'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=50, verbose_name='任务名称')),
                ('task_uuid', models.CharField(max_length=50, verbose_name='任务id')),
                ('start_time', models.DateTimeField(auto_now=True, verbose_name='开始时间')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('status', models.IntegerField(choices=[(0, '未启动'), (1, '正在运行'), (2, '已完成'), (3, '异常'), (4, '正在停止')], default=0, verbose_name='状态')),
            ],
        ),
    ]
