# Generated by Django 3.2.16 on 2022-11-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20221120_2159'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='option',
        ),
        migrations.AlterField(
            model_name='task',
            name='end_time',
            field=models.DateTimeField(default=None, verbose_name='结束时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_time',
            field=models.DateTimeField(auto_now=True, verbose_name='开始时间'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, '未启动'), (1, '正在运行'), (2, '已完成'), (3, '异常')], default=0, verbose_name='状态'),
        ),
    ]
