# Generated by Django 3.2.16 on 2022-11-21 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tasklist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='task_uuid',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id'),
        ),
    ]
