# Generated by Django 3.2.16 on 2022-11-20 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20221120_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(default=1, max_length=50, verbose_name='任务id'),
            preserve_default=False,
        ),
    ]
