# Generated by Django 3.2.16 on 2022-11-21 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20221121_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_uuid',
            new_name='task_id',
        ),
    ]
