# Generated by Django 3.2.16 on 2022-11-21 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_task_uuid_task_task_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id'),
        ),
    ]
