# Generated by Django 3.2.16 on 2022-11-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_task_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='task_uuid',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='进程id'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='task_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='进程id'),
        ),
    ]
