# Generated by Django 3.2.16 on 2022-11-23 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20221121_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='task_id',
        ),
    ]
