# coding=utf-8
s = [{'StockName': 'DBS Bank Ltd.', 'ShareType': '普通股', 'StockPercent': '2.01%', 'ShouldCapi': '767,673,611',
      'ShoudDate': '', 'FinalBenefitPercent': '2.01%', 'InDate': '-', 'Name': '-'},
     {'StockName': 'Oversea Lucky Investment Limited', 'ShareType': '普通股', 'StockPercent': '5.00%',
      'ShouldCapi': '1,907,845,112', 'ShoudDate': '', 'FinalBenefitPercent': '5.00%', 'InDate': '-', 'Name': '-'},
     {'StockName': '中华人民共和国全国社会保障基金理事会', 'ShareType': '普通股', 'StockPercent': '14.05%', 'ShouldCapi': '5,360,699,325',
      'ShoudDate': '', 'FinalBenefitPercent': '14.05%', 'InDate': '-', 'Name': '-'},
     {'StockName': '中华人民共和国财政部', 'ShareType': '普通股', 'StockPercent': '58.00%', 'ShouldCapi': '22,137,239,084',
      'ShoudDate': '', 'FinalBenefitPercent': '58.00%', 'InDate': '-', 'Name': '-'}]
f = [{'Status': '存续', 'FundedRatio': '87.4156%', 'ShouldCapi': '255140万元人民币', 'ShouldDate': 1298822400,
      'ProvinceName': '北京', 'Industry': '金融业', 'ProductName': '信达证券', 'StockName': '信达证券股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.89%', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '中国华融', 'StockName': '中国华融资产管理股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.83%', 'ShouldCapi': '873,430,059股', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '制造业', 'ProductName': '中国重工', 'StockName': '中国船舶重工股份有限公司'},
     {'Status': '存续', 'FundedRatio': '8.62%', 'ShouldCapi': '709,886,375股', 'ShouldDate': 0, 'ProvinceName': '湖南',
      'Industry': '金融业', 'ProductName': '方正证券', 'StockName': '方正证券股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.63%', 'ShouldCapi': '342,874,300股', 'ShouldDate': 0, 'ProvinceName': '甘肃',
      'Industry': '采矿业', 'ProductName': '白银有色', 'StockName': '白银有色集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '21.16%', 'ShouldCapi': '336,000,000股', 'ShouldDate': 0, 'ProvinceName': '河北',
      'Industry': '金融业', 'ProductName': '开滦股份', 'StockName': '开滦能源化工股份有限公司'},
     {'Status': '存续', 'FundedRatio': '11.68%', 'ShouldCapi': '309,250,000股', 'ShouldDate': 0, 'ProvinceName': '上海',
      'Industry': '租赁和商务服务业', 'ProductName': '中国核建', 'StockName': '中国核工业建设股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.14%', 'ShouldCapi': '279,206,652股', 'ShouldDate': 0, 'ProvinceName': '上海',
      'Industry': '制造业', 'ProductName': '上海莱士', 'StockName': '上海莱士血液制品股份有限公司'},
     {'Status': '存续', 'FundedRatio': '13.78%', 'ShouldCapi': '200,948,100股', 'ShouldDate': 0, 'ProvinceName': '宁夏',
      'Industry': '制造业', 'ProductName': '西部创业', 'StockName': '宁夏西部创业实业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '5.47%', 'ShouldCapi': '118,081,403股', 'ShouldDate': 0, 'ProvinceName': '河北',
      'Industry': '制造业', 'ProductName': '中国动力', 'StockName': '中国船舶重工集团动力股份有限公司'},
     {'Status': '存续', 'FundedRatio': '7.83%', 'ShouldCapi': '103,500,000股', 'ShouldDate': 0, 'ProvinceName': '辽宁',
      'Industry': '建筑业', 'ProductName': '红阳能源', 'StockName': '辽宁能源煤电产业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '5.34%', 'ShouldCapi': '100,000,000股', 'ShouldDate': 0, 'ProvinceName': '湖北',
      'Industry': '制造业', 'ProductName': '九州通', 'StockName': '九州通医药集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '8.53%', 'ShouldCapi': '92,250,068股', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '建筑业', 'ProductName': '浙江建投', 'StockName': '浙江省建设投资集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '2.26%', 'ShouldCapi': '81,800,000股', 'ShouldDate': 0, 'ProvinceName': '内蒙古',
      'Industry': '建筑业', 'ProductName': '远兴能源', 'StockName': '内蒙古远兴能源股份有限公司'},
     {'Status': '存续', 'FundedRatio': '1.49%', 'ShouldCapi': '81,112,561股', 'ShouldDate': 0, 'ProvinceName': '青海',
      'Industry': '制造业', 'ProductName': '盐湖股份', 'StockName': '青海盐湖工业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.64%', 'ShouldCapi': '61,035,000股', 'ShouldDate': 0, 'ProvinceName': '重庆',
      'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '三峰环境', 'StockName': '重庆三峰环境集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '2.1659%', 'ShouldCapi': '3434万元人民币', 'ShouldDate': 1298822400,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '沈鼓集团', 'StockName': '沈阳鼓风机集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.77%', 'ShouldCapi': '36,520,003股', 'ShouldDate': 0, 'ProvinceName': '山西',
      'Industry': '采矿业', 'ProductName': '蓝焰控股', 'StockName': '山西蓝焰控股股份有限公司'},
     {'Status': '存续', 'FundedRatio': '1.34%', 'ShouldCapi': '31,115,916股', 'ShouldDate': 0, 'ProvinceName': '湖北',
      'Industry': '制造业', 'ProductName': '安道麦', 'StockName': '安道麦股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.74%', 'ShouldCapi': '22,200,000股', 'ShouldDate': 0, 'ProvinceName': '天津',
      'Industry': '科学研究和技术服务业', 'ProductName': '中源协和', 'StockName': '中源协和细胞基因工程股份有限公司'},
     {'Status': '在业', 'FundedRatio': '0.46%', 'ShouldCapi': '9,596,100股', 'ShouldDate': 0, 'ProvinceName': '山东',
      'Industry': '文化、体育和娱乐业', 'ProductName': '山东出版', 'StockName': '山东出版传媒股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.59%', 'ShouldCapi': '2,000,000股', 'ShouldDate': 0, 'ProvinceName': '黑龙江',
      'Industry': '制造业', 'ProductName': 'SST佳通', 'StockName': '佳通轮胎股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.23%', 'ShouldCapi': '272,319,926股', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '制造业', 'ProductName': '中国建材', 'StockName': '中国建材股份有限公司'},
     {'Status': '存续', 'FundedRatio': '79.996%', 'ShouldCapi': '1600000万元人民币', 'ShouldDate': 1972742400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信达润泽投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.7451%', 'ShouldCapi': '1510000万元人民币', 'ShouldDate': 1481126400,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '深圳市正信世纪投资企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '89.9836%', 'ShouldCapi': '990000万元人民币', 'ShouldDate': 1475078400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区聚晟佳达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.9944%', 'ShouldCapi': '899900万元人民币', 'ShouldDate': 1456934400,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '深圳市国威股权投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.9929%', 'ShouldCapi': '787500万元人民币', 'ShouldDate': 1522339200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖京信泰富投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.9925%', 'ShouldCapi': '750000万元人民币', 'ShouldDate': 1829232000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信达润泽投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.986%', 'ShouldCapi': '699860万元人民币', 'ShouldDate': 0, 'ProvinceName': '河南',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '河南省房地产纾困投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '80.0092%', 'ShouldCapi': '680990万元人民币', 'ShouldDate': 1477324800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信穗投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '83.6057%', 'ShouldCapi': '644600万元人民币', 'ShouldDate': 1535731200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区泰温茂豫投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.8916%', 'ShouldCapi': '607459.361111万元人民币', 'ShouldDate': 1595779200,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信海企业管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '45.1154%', 'ShouldCapi': '599900万元人民币', 'ShouldDate': 0, 'ProvinceName': '海南',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '海口顺鑫客舱服务投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.4896%', 'ShouldCapi': '534416万元人民币', 'ShouldDate': 1482681600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '中鑫博达（芜湖）投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '30.1219%', 'ShouldCapi': '513116.43万元人民币', 'ShouldDate': 1227024000,
      'ProvinceName': '山西', 'Industry': '采矿业', 'ProductName': '同煤集团', 'StockName': '晋能控股煤业集团有限公司'},
     {'Status': '存续', 'FundedRatio': '86.1136%', 'ShouldCapi': '503582.11万元人民币', 'ShouldDate': 1526572800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信淮投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.998%', 'ShouldCapi': '5000000万元人民币', 'ShouldDate': 1514390400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信达降杠杆投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9%', 'ShouldCapi': '499500万元人民币', 'ShouldDate': 1828540800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信达盈新投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '59.0581%', 'ShouldCapi': '407800万元人民币', 'ShouldDate': 1508688000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖粤信投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '79.9991%', 'ShouldCapi': '439995万元人民币', 'ShouldDate': 1469635200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信运汉石投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '41.1393%', 'ShouldCapi': '380552.3万元人民币', 'ShouldDate': 1134230400,
      'ProvinceName': '山西', 'Industry': '采矿业', 'ProductName': '西山煤电集团', 'StockName': '西山煤电（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.6409%', 'ShouldCapi': '349266.1029万元人民币', 'ShouldDate': 1403625600,
      'ProvinceName': '甘肃', 'Industry': '金融业', 'ProductName': '信达金融租赁', 'StockName': '信达金融租赁有限公司'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '海南',
      'Industry': '科学研究和技术服务业', 'ProductName': '-', 'StockName': '海南信深创科技发展合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.97%', 'ShouldCapi': '300009.97万元人民币', 'ShouldDate': 2575814400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '杭州金桂瑞锦资产管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '66.6223%', 'ShouldCapi': '300000万元人民币', 'ShouldDate': 1558886400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖龙端投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '42.2396%', 'ShouldCapi': '300000万元人民币', 'ShouldDate': 878227200,
      'ProvinceName': '内蒙古', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '神华准格尔能源有限责任公司'},
     {'Status': '在业', 'FundedRatio': '99.9667%', 'ShouldCapi': '300000万元人民币', 'ShouldDate': 1941552000,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '信达法拍（广东）创新投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9667%', 'ShouldCapi': '300000万元人民币', 'ShouldDate': 1880121600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信申旭达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9667%', 'ShouldCapi': '299900万元人民币', 'ShouldDate': 1453046400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波京信汇铖投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '50.9908%', 'ShouldCapi': '283272万元人民币', 'ShouldDate': 1459180800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '中鑫荣达（芜湖）投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '34.672%', 'ShouldCapi': '262826.5万元人民币', 'ShouldDate': 1200326400,
      'ProvinceName': '山西', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '华阳新材料科技集团有限公司'},
     {'Status': '在业', 'FundedRatio': '99.9615%', 'ShouldCapi': '259600万元人民币', 'ShouldDate': 1607443200,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '珠海横琴铧信瑞兴投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '71.3946%', 'ShouldCapi': '150000万元人民币', 'ShouldDate': 1629129600,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '珠海横琴铧信泽铄投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '86.4649%', 'ShouldCapi': '230000万元人民币', 'ShouldDate': 1592150400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖聚信城兮投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.9778%', 'ShouldCapi': '225000万元人民币', 'ShouldDate': 1741622400,
      'ProvinceName': '湖南', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '湖南府院联动破产企业管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '93.6575%', 'ShouldCapi': '203040万元人民币', 'ShouldDate': 1388332800,
      'ProvinceName': '北京', 'Industry': '金融业', 'ProductName': '-', 'StockName': '中国金谷国际信托有限责任公司'},
     {'Status': '存续', 'FundedRatio': '100%', 'ShouldCapi': '200000万元人民币', 'ShouldDate': 1207065600,
      'ProvinceName': '北京', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '信达投资有限公司'},
     {'Status': '存续', 'FundedRatio': '49.9875%', 'ShouldCapi': '200000万元人民币', 'ShouldDate': 1814371200,
      'ProvinceName': '天津', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '天津晋信化工股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '62.0822%', 'ShouldCapi': '198725万元人民币', 'ShouldDate': 1448380800,
      'ProvinceName': '上海', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '上海彤熹投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9468%', 'ShouldCapi': '188000万元人民币', 'ShouldDate': 1462723200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信己投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '42.288%', 'ShouldCapi': '181500万元人民币', 'ShouldDate': 1512576000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信致投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.9688%', 'ShouldCapi': '180000万元人民币', 'ShouldDate': 1816099200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信泽青投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.8557%', 'ShouldCapi': '180000万元人民币', 'ShouldDate': 1483891200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信京投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9972%', 'ShouldCapi': '179995万元人民币', 'ShouldDate': 1418659200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波东达信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '84.95%', 'ShouldCapi': '169900万元人民币', 'ShouldDate': 1485014400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区鑫临空投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '99.9399%', 'ShouldCapi': '166400万元人民币', 'ShouldDate': 1607443200,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '珠海横琴铧信启隆投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '79.961%', 'ShouldCapi': '164000万元人民币', 'ShouldDate': 1511971200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信源投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '36.965%', 'ShouldCapi': '162709.956843万元人民币', 'ShouldDate': 1134230400,
      'ProvinceName': '山西', 'Industry': '采矿业', 'ProductName': '霍州煤电集团', 'StockName': '霍州煤电集团有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.9375%', 'ShouldCapi': '159900万元人民币', 'ShouldDate': 1554652800,
      'ProvinceName': '海南', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '海南信恒寓才股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '60.489%', 'ShouldCapi': '153400万元人民币', 'ShouldDate': 1480262400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区鑫鲲达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '35.853%', 'ShouldCapi': '151476.20145万元人民币', 'ShouldDate': 1600012800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖沁安投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '32.7404%', 'ShouldCapi': '150903.68万元人民币', 'ShouldDate': 1577635200,
      'ProvinceName': '贵州', 'Industry': '采矿业', 'ProductName': '瓮福集团', 'StockName': '瓮福（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '8.3194%', 'ShouldCapi': '150602.4096万元人民币', 'ShouldDate': 1542643200,
      'ProvinceName': '安徽', 'Industry': '采矿业', 'ProductName': '淮南矿业', 'StockName': '淮南矿业（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.6016%', 'ShouldCapi': '150000万元人民币', 'ShouldDate': 1479225600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖益信日升投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9933%', 'ShouldCapi': '150000万元人民币', 'ShouldDate': 1785686400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖汇铖投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '48%', 'ShouldCapi': '144000万元人民币', 'ShouldDate': 1565884800, 'ProvinceName': '广东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳信石信兴产业并购股权投资基金合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '26.6666%', 'ShouldCapi': '144000万元人民币', 'ShouldDate': 1798646400,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '广州市德耀鸿鼎投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.3326%', 'ShouldCapi': '138665.227273万元人民币', 'ShouldDate': 1493049600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖星都投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '74.4367%', 'ShouldCapi': '137000万元人民币', 'ShouldDate': 1490803200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖米兰时代投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9265%', 'ShouldCapi': '136000万元人民币', 'ShouldDate': 1700755200,
      'ProvinceName': '天津', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '天津文泰股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '8.94%', 'ShouldCapi': '134109万元人民币', 'ShouldDate': 1485187200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波春鸿二期投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '30.4629%', 'ShouldCapi': '132607.2293万元人民币', 'ShouldDate': 1039622400,
      'ProvinceName': '辽宁', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '铁法煤业（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '49.9809%', 'ShouldCapi': '131000万元人民币', 'ShouldDate': 1704038400,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '天津长寿信诺投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '56.4972%', 'ShouldCapi': '130000万元人民币', 'ShouldDate': 1473091200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖同信大成投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '36.0221%', 'ShouldCapi': '127001.48万元人民币', 'ShouldDate': 1134230400,
      'ProvinceName': '山西', 'Industry': '批发和零售业', 'ProductName': '山西汾西矿业', 'StockName': '山西汾西矿业（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.876%', 'ShouldCapi': '120000万元人民币', 'ShouldDate': 1626278400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖科宇信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '85.4874%', 'ShouldCapi': '118400万元人民币', 'ShouldDate': 1497801600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信庆投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '94.624%', 'ShouldCapi': '110000万元人民币', 'ShouldDate': 1803052800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信首昌投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '52.4579%', 'ShouldCapi': '106138万元人民币', 'ShouldDate': 1073577600,
      'ProvinceName': '宁夏', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '宁夏灵信煤业有限责任公司'},
     {'Status': '存续', 'FundedRatio': '45.5503%', 'ShouldCapi': '105582万元人民币', 'ShouldDate': 1025107200,
      'ProvinceName': '辽宁', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '阜新中宝能源有限责任公司'},
     {'Status': '存续', 'FundedRatio': '6.2296%', 'ShouldCapi': '102333.2622万元人民币', 'ShouldDate': 1254240000,
      'ProvinceName': '内蒙古', 'Industry': '制造业', 'ProductName': '包钢集团', 'StockName': '包头钢铁（集团）有限责任公司'},
     {'Status': '在业', 'FundedRatio': '66.2252%', 'ShouldCapi': '100000万元人民币', 'ShouldDate': 0, 'ProvinceName': '山东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '山东聚赢产业基金合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '99.8004%', 'ShouldCapi': '100000万元人民币', 'ShouldDate': 1881849600,
      'ProvinceName': '山东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '青岛清科和信创业投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.9001%', 'ShouldCapi': '100000万元人民币', 'ShouldDate': 1767110400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区汇融沁芮股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '25%', 'ShouldCapi': '100000万元人民币', 'ShouldDate': 1355068800, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '中国农业产业发展基金有限公司'},
     {'Status': '存续', 'FundedRatio': '33.3%', 'ShouldCapi': '99900万元人民币', 'ShouldDate': 1537891200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖豫能信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '47.1574%', 'ShouldCapi': '99692.92万元人民币', 'ShouldDate': 1575129600,
      'ProvinceName': '贵州', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '贵州新福投资有限公司'},
     {'Status': '存续', 'FundedRatio': '59.9276%', 'ShouldCapi': '99391.2万元人民币', 'ShouldDate': 1840636800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖佑信投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.95%', 'ShouldCapi': '98000万元人民币', 'ShouldDate': 1484755200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖赣鄂新投资中心（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '57.1441%', 'ShouldCapi': '93470万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '珠海横琴铧信泽盛投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '97.2418%', 'ShouldCapi': '89900万元人民币', 'ShouldDate': 1476374400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信达华地投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.9399%', 'ShouldCapi': '89600万元人民币', 'ShouldDate': 1787673600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '杭州空首布企业管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '44.3604%', 'ShouldCapi': '85000万元人民币', 'ShouldDate': 1781020800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖天纵达信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '68.4299%', 'ShouldCapi': '81500万元人民币', 'ShouldDate': 1633795200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区文添投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '79.9201%', 'ShouldCapi': '80000万元人民币', 'ShouldDate': 1756137600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信鹰嘉纸投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.2%', 'ShouldCapi': '79950万元人民币', 'ShouldDate': 1472745600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖赣新投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '23.2331%', 'ShouldCapi': '72060.66万元人民币', 'ShouldDate': 1229443200,
      'ProvinceName': '河南', 'Industry': '采矿业', 'ProductName': '义马煤业', 'StockName': '义马煤业集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '33.8774%', 'ShouldCapi': '78413.848184万元人民币', 'ShouldDate': 0,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '深圳中广核三期产业投资基金合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '69.7273%', 'ShouldCapi': '76700万元人民币', 'ShouldDate': 1848672000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信洲投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '88.1316%', 'ShouldCapi': '75000万元人民币', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信霞投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '42.8082%', 'ShouldCapi': '75000万元人民币', 'ShouldDate': 1608480000,
      'ProvinceName': '广西', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '广西信材致远投资发展合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '29.1545%', 'ShouldCapi': '70000万元人民币', 'ShouldDate': 2030457600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '嘉兴信业盛嘉投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '40.2736%', 'ShouldCapi': '67700万元人民币', 'ShouldDate': 1684339200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信喆投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '48.0265%', 'ShouldCapi': '62774万元人民币', 'ShouldDate': 1450627200,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '安徽中鑫耀达投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '20.7418%', 'ShouldCapi': '62486万元人民币', 'ShouldDate': 1038499200,
      'ProvinceName': '山东', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '山东中兴能源有限责任公司'},
     {'Status': '存续', 'FundedRatio': '59.9401%', 'ShouldCapi': '60000万元人民币', 'ShouldDate': 1787587200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信超惠投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.8336%', 'ShouldCapi': '60000万元人民币', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信石信鸿股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.8333%', 'ShouldCapi': '59900万元人民币', 'ShouldDate': 1474387200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信渝矿富投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '6.962%', 'ShouldCapi': '56116.315万元人民币', 'ShouldDate': 1561824000,
      'ProvinceName': '山西', 'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '山西燃气', 'StockName': '山西燃气集团有限公司'},
     {'Status': '存续', 'FundedRatio': '2.7549%', 'ShouldCapi': '53534万元人民币', 'ShouldDate': 1254326400,
      'ProvinceName': '河南', 'Industry': '采矿业', 'ProductName': '平煤神马', 'StockName': '中国平煤神马控股集团有限公司'},
     {'Status': '存续', 'FundedRatio': '13.6528%', 'ShouldCapi': '53316.96万元人民币', 'ShouldDate': 1289318400,
      'ProvinceName': '山西', 'Industry': '采矿业', 'ProductName': '晋煤集团', 'StockName': '晋能控股装备制造集团有限公司'},
     {'Status': '存续', 'FundedRatio': '6.3405%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 2113920000,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '博裕景泰（上海）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '10.099%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1474473600,
      'ProvinceName': '黑龙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '黑龙江中信资本医药产业股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '24.7525%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1632412800,
      'ProvinceName': '湖南', 'Industry': '金融业', 'ProductName': '-', 'StockName': '湖南财信精锐投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '12.0453%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1499356800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信石合力投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '9.802%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1438704000,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳信达城市发展投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '51.4933%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1845907200,
      'ProvinceName': '江苏', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '睿哲汇智股权投资基金江阴合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '24.9875%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1479657600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信石信冶投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '33.3111%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1438012800,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '上海自贸试验区一期股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '29.1681%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1827504000,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '上海自贸试验区三期股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.95%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1827504000,
      'ProvinceName': '天津', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '信达远海航运投资（天津）合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.4024%', 'ShouldCapi': '49900万元人民币', 'ShouldDate': 1740672000,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '建航晶合二期股权投资基金（天津）合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '62.375%', 'ShouldCapi': '49900万元人民币', 'ShouldDate': 1482422400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信泽润投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '20.2316%', 'ShouldCapi': '48686.0304万元人民币', 'ShouldDate': 1343232000,
      'ProvinceName': '贵州', 'Industry': '采矿业', 'ProductName': '水城矿业', 'StockName': '贵州水城矿业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '36.1521%', 'ShouldCapi': '46600万元人民币', 'ShouldDate': 1452441600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信韵投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '67.0634%', 'ShouldCapi': '46200万元人民币', 'ShouldDate': 1427817600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信达天风投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '13.1546%', 'ShouldCapi': '44909万元人民币', 'ShouldDate': 1229961600,
      'ProvinceName': '贵州', 'Industry': '制造业', 'ProductName': '水城钢铁', 'StockName': '首钢水城钢铁（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '69.8413%', 'ShouldCapi': '44000万元人民币', 'ShouldDate': 1594828800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖达文投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '23.1329%', 'ShouldCapi': '43402.23万元人民币', 'ShouldDate': 978192000,
      'ProvinceName': '重庆', 'Industry': '制造业', 'ProductName': '大江信达', 'StockName': '重庆大江信达车辆股份有限公司'},
     {'Status': '存续', 'FundedRatio': '95.4545%', 'ShouldCapi': '42000万元人民币', 'ShouldDate': 1801324800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖铧珲信澄投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.7467%', 'ShouldCapi': '41500万元人民币', 'ShouldDate': 1814371200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信宁投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '92.8342%', 'ShouldCapi': '40420万元人民币', 'ShouldDate': 1752076800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信柳投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '92.834%', 'ShouldCapi': '40160万元人民币', 'ShouldDate': 1585670400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信广诚投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '79.992%', 'ShouldCapi': '40000万元人民币', 'ShouldDate': 1472054400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信石天路投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '32.8628%', 'ShouldCapi': '40000万元人民币', 'ShouldDate': 1924876800,
      'ProvinceName': '浙江', 'Industry': '科学研究和技术服务业', 'ProductName': '-', 'StockName': '长三角（嘉善）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '16.0279%', 'ShouldCapi': '38887.8185万元人民币', 'ShouldDate': 993830400,
      'ProvinceName': '河北', 'Industry': '金融业', 'ProductName': '三友集团', 'StockName': '唐山三友集团有限公司'},
     {'Status': '存续', 'FundedRatio': '16.4%', 'ShouldCapi': '38540万元人民币', 'ShouldDate': 1345996800,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '沈阳焦煤股份', 'StockName': '沈阳焦煤股份有限公司'},
     {'Status': '存续', 'FundedRatio': '29.9634%', 'ShouldCapi': '38175.9977万元人民币', 'ShouldDate': 1169740800,
      'ProvinceName': '内蒙古', 'Industry': '制造业', 'ProductName': '-', 'StockName': '鄂尔多斯市伊化矿业资源有限责任公司'},
     {'Status': '存续', 'FundedRatio': '2.9303%', 'ShouldCapi': '37404.36万元人民币', 'ShouldDate': 1008518400,
      'ProvinceName': '上海', 'Industry': '租赁和商务服务业', 'ProductName': '上海纺织', 'StockName': '上海纺织（集团）有限公司'},
     {'Status': '在业', 'FundedRatio': '21.72%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '广东广电网络投资一号有限合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '8.6571%', 'ShouldCapi': '36202.7979万元人民币', 'ShouldDate': 0, 'ProvinceName': '陕西',
      'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '-', 'StockName': '陕西省水电开发有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.4248%', 'ShouldCapi': '34400.4617万元人民币', 'ShouldDate': 1773504000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信林达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '21.8474%', 'ShouldCapi': '34261.0525万元人民币', 'ShouldDate': 1645977600,
      'ProvinceName': '甘肃', 'Industry': '房地产业', 'ProductName': '-', 'StockName': '甘肃瑞赛可循环经济产业集团有限公司'},
     {'Status': '存续', 'FundedRatio': '17.0699%', 'ShouldCapi': '33030万元人民币', 'ShouldDate': 1009728000,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '-', 'StockName': '抚顺矿业集团工贸有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.696%', 'ShouldCapi': '32800万元人民币', 'ShouldDate': 1746374400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区文沛股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.8462%', 'ShouldCapi': '32400万元人民币', 'ShouldDate': 1767110400,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '延发北控信能（天津）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '68.2352%', 'ShouldCapi': '32243.53万元人民币', 'ShouldDate': 1508169600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '长兴恒兆投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '56.5716%', 'ShouldCapi': '32000万元人民币', 'ShouldDate': 1760371200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信昇壹号投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.3789%', 'ShouldCapi': '32000万元人民币', 'ShouldDate': 1809100800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信远金梧股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '6.108%', 'ShouldCapi': '31951.8031万元人民币', 'ShouldDate': 943977600,
      'ProvinceName': '天津', 'Industry': '制造业', 'ProductName': '天津钢管', 'StockName': '天津钢管集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '15.8266%', 'ShouldCapi': '31684万元人民币', 'ShouldDate': 1009728000,
      'ProvinceName': '上海', 'Industry': '制造业', 'ProductName': '-', 'StockName': '上海有色新材料（集团）有限公司'},
     {'Status': '存续', 'FundedRatio': '17.3059%', 'ShouldCapi': '31675.063万元人民币', 'ShouldDate': 1579017600,
      'ProvinceName': '河南', 'Industry': '金融业', 'ProductName': '监控网', 'StockName': '华融融达期货股份有限公司'},
     {'Status': '在业', 'FundedRatio': '21.5922%', 'ShouldCapi': '30876.96万元人民币', 'ShouldDate': 1288713600,
      'ProvinceName': '山东', 'Industry': '制造业', 'ProductName': '-', 'StockName': '济南正昊化纤新材料有限公司'},
     {'Status': '存续', 'FundedRatio': '99.6736%', 'ShouldCapi': '30539.45万元人民币', 'ShouldDate': 1737302400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信高投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '6.135%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1737388800,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '国开博裕一期（上海）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.6678%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1774886400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信通投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '10%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1886601600, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '北京信润恒股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '2.9997%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1607443200,
      'ProvinceName': '上海', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '上海冬晟投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '24.1977%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1468252800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖庆诚投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '42.796%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1558886400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖新扬投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.1803%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1678982400,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '信达国萃股权投资基金（上海）合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '46.1396%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1386172800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波首泰信合投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '7.4866%', 'ShouldCapi': '300,000,000股', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '金融业', 'ProductName': '国任保险', 'StockName': '国任财产保险股份有限公司'},
     {'Status': '存续', 'FundedRatio': '2.4388%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1375977600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波达泰投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '52.5011%', 'ShouldCapi': '29755.29万元人民币', 'ShouldDate': 1784995200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信樾投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '53.8175%', 'ShouldCapi': '29530.34万元人民币', 'ShouldDate': 1157040000,
      'ProvinceName': '甘肃', 'Industry': '制造业', 'ProductName': '金昌化工', 'StockName': '甘肃金昌化学工业集团有限公司'},
     {'Status': '存续', 'FundedRatio': '99.9966%', 'ShouldCapi': '29000万元人民币', 'ShouldDate': 2104156800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '嘉兴申贸伍号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '7.393%', 'ShouldCapi': '28500万元人民币', 'ShouldDate': 1618761600,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '思齐（天津）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '77.5384%', 'ShouldCapi': '28046.4万元人民币', 'ShouldDate': 0, 'ProvinceName': '辽宁',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '丹东鸭绿江造纸有限责任公司'},
     {'Status': '存续', 'FundedRatio': '10%', 'ShouldCapi': '28000万元人民币', 'ShouldDate': 1698681600, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '北京中宏瑞德投资管理中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '93.311%', 'ShouldCapi': '27900万元人民币', 'ShouldDate': 1705939200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '嘉兴聚力贰号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '36.4687%', 'ShouldCapi': '27184.9234万元人民币', 'ShouldDate': 1192118400,
      'ProvinceName': '新疆', 'Industry': '租赁和商务服务业', 'ProductName': '天山建材', 'StockName': '新疆天山建材（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '45%', 'ShouldCapi': '27000万元人民币', 'ShouldDate': 1740758400, 'ProvinceName': '安徽',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信津创投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '25.974%', 'ShouldCapi': '26000万元人民币', 'ShouldDate': 1478793600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区达信新华医疗投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '6.0857%', 'ShouldCapi': '25293.9406万元人民币', 'ShouldDate': 1593273600,
      'ProvinceName': '四川', 'Industry': '制造业', 'ProductName': '达州钢铁', 'StockName': '四川省达州钢铁集团有限责任公司'},
     {'Status': '存续', 'FundedRatio': '50%', 'ShouldCapi': '25000万元人民币', 'ShouldDate': 1450972800, 'ProvinceName': '天津',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '信达一汽商业保理有限公司'},
     {'Status': '存续', 'FundedRatio': '60.7533%', 'ShouldCapi': '25000万元人民币', 'ShouldDate': 1607961600,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖弢烁投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '24.975%', 'ShouldCapi': '25000万元人民币', 'ShouldDate': 1469635200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区新能惠通投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '76.6003%', 'ShouldCapi': '24681.37万元人民币', 'ShouldDate': 1326643200,
      'ProvinceName': '新疆', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '新疆新化化肥有限责任公司'},
     {'Status': '存续', 'FundedRatio': '99.5898%', 'ShouldCapi': '24278.827388万元人民币', 'ShouldDate': 1626278400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖达泰投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '88.1147%', 'ShouldCapi': '23086.0555万元人民币', 'ShouldDate': 1446566400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波沁融股权投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '44.5758%', 'ShouldCapi': '23000万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '广东广祺智行肆号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '73.3333%', 'ShouldCapi': '22000万元人民币', 'ShouldDate': 1461772800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信达汉石龙脊股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.7641%', 'ShouldCapi': '21095万元人民币', 'ShouldDate': 0, 'ProvinceName': '福建',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '厦门建发长鸿壹号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '69.7674%', 'ShouldCapi': '21000万元人民币', 'ShouldDate': 1753891200,
      'ProvinceName': '云南', 'Industry': '金融业', 'ProductName': '-', 'StockName': '昆明市官渡区官信创项目投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '9.8001%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1557676800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '安徽信富股权投资基金（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '11.0828%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖华恒投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '66.4452%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1783180800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信共安筑投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.0099%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1885392000,
      'ProvinceName': '湖南', 'Industry': '金融业', 'ProductName': '-', 'StockName': '湖南湘江天权股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.95%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1633622400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖盛益信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '5.0978%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1495641600,
      'ProvinceName': '北京', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '北京集成电路制造和装备股权投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '16.6385%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '深圳市远致华信新兴产业股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '30%', 'ShouldCapi': '19500万元人民币', 'ShouldDate': 1609344000, 'ProvinceName': '浙江',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '安岱汇智股权投资基金（湖州）合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '19.4862%', 'ShouldCapi': '18124万元人民币', 'ShouldDate': 1212508800,
      'ProvinceName': '北京', 'Industry': '制造业', 'ProductName': '雪花集团', 'StockName': '北京轻工雪花电器有限责任公司'},
     {'Status': '存续', 'FundedRatio': '17.549%', 'ShouldCapi': '17900万元人民币', 'ShouldDate': 1479916800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信丰投资中心（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '53.5381%', 'ShouldCapi': '16239.67万元人民币', 'ShouldDate': 1514131200,
      'ProvinceName': '山东', 'Industry': '采矿业', 'ProductName': '鲁泰控股', 'StockName': '山东鲁泰控股集团有限公司'},
     {'Status': '存续', 'FundedRatio': '19.2625%', 'ShouldCapi': '16163.96万元人民币', 'ShouldDate': 1645977600,
      'ProvinceName': '新疆', 'Industry': '建筑业', 'ProductName': '北新投资', 'StockName': '新疆北新投资建设有限公司'},
     {'Status': '存续', 'FundedRatio': '0.7%', 'ShouldCapi': '161,000,000股', 'ShouldDate': 0, 'ProvinceName': '甘肃',
      'Industry': '采矿业', 'ProductName': '金川集团', 'StockName': '金川集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '99.9937%', 'ShouldCapi': '15750万元人民币', 'ShouldDate': 1778947200,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '嘉兴芯荣股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '29.7465%', 'ShouldCapi': '15734万元人民币', 'ShouldDate': 0, 'ProvinceName': '贵州',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '贵州化肥厂有限责任公司'},
     {'Status': '存续', 'FundedRatio': '7.8059%', 'ShouldCapi': '15611.8万元人民币', 'ShouldDate': 1540915200,
      'ProvinceName': '贵州', 'Industry': '采矿业', 'ProductName': '六枝工矿', 'StockName': '六枝工矿（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '10.702%', 'ShouldCapi': '15110万元人民币', 'ShouldDate': 1038585600,
      'ProvinceName': '河北', 'Industry': '采矿业', 'ProductName': '冀中能源邯郸矿业', 'StockName': '冀中能源邯郸矿业集团有限公司'},
     {'Status': '存续', 'FundedRatio': '24.5902%', 'ShouldCapi': '15000万元人民币', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '北京首泰天缘股权投资基金（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '49.95%', 'ShouldCapi': '15000万元人民币', 'ShouldDate': 1418918400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信宸投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '11.1473%', 'ShouldCapi': '14267.426976万元人民币', 'ShouldDate': 1276272000,
      'ProvinceName': '山西', 'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '太原煤炭气化', 'StockName': '太原煤炭气化（集团）有限责任公司'},
     {'Status': '存续', 'FundedRatio': '54.9106%', 'ShouldCapi': '12904万元人民币', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信嘉达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '11.7751%', 'ShouldCapi': '12566.23万元人民币', 'ShouldDate': 1511107200,
      'ProvinceName': '四川', 'Industry': '采矿业', 'ProductName': '西昌矿业', 'StockName': '重钢西昌矿业有限公司'},
     {'Status': '存续', 'FundedRatio': '21.8474%', 'ShouldCapi': '12044.7623万元人民币', 'ShouldDate': 1000915200,
      'ProvinceName': '甘肃', 'Industry': '采矿业', 'ProductName': '窑街煤电', 'StockName': '窑街煤电集团有限公司'},
     {'Status': '存续', 'FundedRatio': '1.8462%', 'ShouldCapi': '12000万元人民币', 'ShouldDate': 1636905600,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '天津爱奇鸿海海河智慧出行股权投资基金合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '60%', 'ShouldCapi': '12000万元人民币', 'ShouldDate': 2082643200, 'ProvinceName': '山东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '淄博盈科值得一号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '3.75%', 'ShouldCapi': '115,121,951股', 'ShouldDate': 0, 'ProvinceName': '重庆',
      'Industry': '制造业', 'ProductName': '国际复合材料', 'StockName': '重庆国际复合材料股份有限公司'},
     {'Status': '在业', 'FundedRatio': '26.7991%', 'ShouldCapi': '11183万元人民币', 'ShouldDate': 0, 'ProvinceName': '山东',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '青岛海湾精细化工有限公司'},
     {'Status': '在业', 'FundedRatio': '9.1501%', 'ShouldCapi': '11068万元人民币', 'ShouldDate': 1656432000,
      'ProvinceName': '山东', 'Industry': '制造业', 'ProductName': '-', 'StockName': '长寿花食品股份有限公司'},
     {'Status': '存续', 'FundedRatio': '48.7124%', 'ShouldCapi': '10059.14万元人民币', 'ShouldDate': 1009728000,
      'ProvinceName': '辽宁', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '大连四方联合化工有限责任公司'},
     {'Status': '存续', 'FundedRatio': '3.5461%', 'ShouldCapi': '10000万元人民币', 'ShouldDate': 1314720000,
      'ProvinceName': '上海', 'Industry': '金融业', 'ProductName': '-', 'StockName': '瑞源（上海）股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '10%', 'ShouldCapi': '10000万元人民币', 'ShouldDate': 1451232000, 'ProvinceName': '上海',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '国核商业保理股份有限公司'},
     {'Status': '存续', 'FundedRatio': '99.0099%', 'ShouldCapi': '10000万元人民币', 'ShouldDate': 1836662400,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信星智造投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '99.0099%', 'ShouldCapi': '10000万元人民币', 'ShouldDate': 1819641600,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信郑投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '49.7512%', 'ShouldCapi': '10000万元人民币', 'ShouldDate': 1830182400,
      'ProvinceName': '山东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '淄博盈科值得三号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '23.7098%', 'ShouldCapi': '9856.419493万元人民币', 'ShouldDate': 1539187200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '润信恒（芜湖）投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '16.4%', 'ShouldCapi': '9840万元人民币', 'ShouldDate': 1262188800,
      'ProvinceName': '黑龙江', 'Industry': '批发和零售业', 'ProductName': '鸡西盛隆矿业', 'StockName': '沈阳焦煤鸡西盛隆矿业有限责任公司'},
     {'Status': '存续', 'FundedRatio': '10.735%', 'ShouldCapi': '9787.68万元人民币', 'ShouldDate': 1284393600,
      'ProvinceName': '江西', 'Industry': '制造业', 'ProductName': '-', 'StockName': '江西六国化工有限责任公司'},
     {'Status': '存续', 'FundedRatio': '1.74%', 'ShouldCapi': '9683.4515万元人民币', 'ShouldDate': 1440000000,
      'ProvinceName': '北京', 'Industry': '批发和零售业', 'ProductName': '中国庆华', 'StockName': '中国庆华能源集团有限公司'},
     {'Status': '存续', 'FundedRatio': '2.6626%', 'ShouldCapi': '9000万元人民币', 'ShouldDate': 1080662400,
      'ProvinceName': '云南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '云南云维集团有限公司'},
     {'Status': '存续', 'FundedRatio': '90%', 'ShouldCapi': '9000万元人民币', 'ShouldDate': 1467302400, 'ProvinceName': '北京',
      'Industry': '金融业', 'ProductName': '汇达资产', 'StockName': '汇达资产托管有限责任公司'},
     {'Status': '存续', 'FundedRatio': '25%', 'ShouldCapi': '1250万美元', 'ShouldDate': 733334400, 'ProvinceName': '上海',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '上海佳通超细化纤有限公司'},
     {'Status': '在业', 'FundedRatio': '20.74%', 'ShouldCapi': '8420.44万元人民币', 'ShouldDate': 1353600000,
      'ProvinceName': '山东', 'Industry': '制造业', 'ProductName': '-', 'StockName': '山东能源重装集团鲁南装备制造有限公司'},
     {'Status': '在业', 'FundedRatio': '24.753%', 'ShouldCapi': '7743万元人民币', 'ShouldDate': 1009209600,
      'ProvinceName': '山东', 'Industry': '制造业', 'ProductName': '裕兴化工', 'StockName': '济南裕兴化工有限责任公司'},
     {'Status': '存续', 'FundedRatio': '8.0097%', 'ShouldCapi': '7654.5万元人民币', 'ShouldDate': 1024588800,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '恒天重工', 'StockName': '恒天重工股份有限公司'},
     {'Status': '存续', 'FundedRatio': '8.2306%', 'ShouldCapi': '7407.5266万元人民币', 'ShouldDate': 1235491200,
      'ProvinceName': '湖南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '株洲化工集团诚信有限公司'},
     {'Status': '存续', 'FundedRatio': '25.2632%', 'ShouldCapi': '7200万元人民币', 'ShouldDate': 1153670400,
      'ProvinceName': '海南', 'Industry': '房地产业', 'ProductName': '-', 'StockName': '海南阳光城开发股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.6899%', 'ShouldCapi': '6709.6362万元人民币', 'ShouldDate': 2145801600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波元轩投资管理合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '30.5508%', 'ShouldCapi': '6591.86万元人民币', 'ShouldDate': 1543507200,
      'ProvinceName': '青海', 'Industry': '制造业', 'ProductName': '-', 'StockName': '民和祁连山水泥有限公司'},
     {'Status': '存续', 'FundedRatio': '13%', 'ShouldCapi': '6500万元人民币', 'ShouldDate': 1603382400, 'ProvinceName': '云南',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '云南瑞丽南屏农村商业银行股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.6757%', 'ShouldCapi': '6193万元人民币', 'ShouldDate': 962121600,
      'ProvinceName': '宁夏', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '太西集团有限责任公司'},
     {'Status': '存续', 'FundedRatio': '17.6675%', 'ShouldCapi': '5786.1万元人民币', 'ShouldDate': 1282752000,
      'ProvinceName': '北京', 'Industry': '制造业', 'ProductName': '二商食品', 'StockName': '北京二商食品股份有限公司'},
     {'Status': '存续', 'FundedRatio': '13.9193%', 'ShouldCapi': '5131万元人民币', 'ShouldDate': 1040745600,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '沈阳水泵', 'StockName': '沈阳水泵股份有限公司'},
     {'Status': '存续', 'FundedRatio': '20%', 'ShouldCapi': '740万美元', 'ShouldDate': 859305600, 'ProvinceName': '北京',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '北京普莱克斯实用气体有限公司'},
     {'Status': '存续', 'FundedRatio': '2.0513%', 'ShouldCapi': '5011.6923万元人民币', 'ShouldDate': 1375977600,
      'ProvinceName': '广东', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '嘉强顺风（深圳）股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '1.8105%', 'ShouldCapi': '5002.3615万元人民币', 'ShouldDate': 1609344000,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '-', 'StockName': '通用技术集团沈阳机床有限责任公司'},
     {'Status': '存续', 'FundedRatio': '9.3751%', 'ShouldCapi': '5000万元人民币', 'ShouldDate': 1598198400,
      'ProvinceName': '山西', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '山西文旅集团晋中汇诚投资管理有限公司'},
     {'Status': '存续', 'FundedRatio': '10%', 'ShouldCapi': '5000万元人民币', 'ShouldDate': 1629388800, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '恒东顺达（北京）投资基金有限公司'},
     {'Status': '在业', 'FundedRatio': '2.5%', 'ShouldCapi': '5000万元人民币', 'ShouldDate': 1449158400, 'ProvinceName': '山东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '西王集团财务有限公司'},
     {'Status': '在业', 'FundedRatio': '99.4012%', 'ShouldCapi': '16600万元人民币', 'ShouldDate': 1801324800,
      'ProvinceName': '山东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '青岛怀格众信私募股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '4.946%', 'ShouldCapi': '4748.19万元人民币', 'ShouldDate': 1514563200,
      'ProvinceName': '宁夏', 'Industry': '农、林、牧、渔业', 'ProductName': '宁夏上陵', 'StockName': '宁夏上陵实业（集团）有限公司'},
     {'Status': '存续', 'FundedRatio': '25.4057%', 'ShouldCapi': '4217万元人民币', 'ShouldDate': 957024000,
      'ProvinceName': '江西', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '江西核工业瑞丰有限责任公司'},
     {'Status': '存续', 'FundedRatio': '1.4957%', 'ShouldCapi': '4092万元人民币', 'ShouldDate': 1038758400,
      'ProvinceName': '北京', 'Industry': '制造业', 'ProductName': '中国纺织机械集团', 'StockName': '中国纺织机械（集团）有限公司'},
     {'Status': '存续', 'FundedRatio': '35.443%', 'ShouldCapi': '3721.515万元人民币', 'ShouldDate': 4073472000,
      'ProvinceName': '天津', 'Industry': '金融业', 'ProductName': '-', 'StockName': '信达股权投资（天津）有限公司'},
     {'Status': '存续', 'FundedRatio': '1.2668%', 'ShouldCapi': '3665.4073万元人民币', 'ShouldDate': 2053353600,
      'ProvinceName': '上海', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '上海天岑瑜憬投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '4.67%', 'ShouldCapi': '36,556,813股', 'ShouldDate': 0, 'ProvinceName': '吉林',
      'Industry': '采矿业', 'ProductName': '吉恩镍业', 'StockName': '吉林吉恩镍业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '5.2013%', 'ShouldCapi': '3525万元人民币', 'ShouldDate': 1466870400,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '-', 'StockName': '沈阳金杯汽车零部件工业有限公司'},
     {'Status': '存续', 'FundedRatio': '14%', 'ShouldCapi': '3507.2365万元人民币', 'ShouldDate': 1309449600,
      'ProvinceName': '贵州', 'Industry': '批发和零售业', 'ProductName': '瓮福蓝天', 'StockName': '贵州瓮福蓝天氟化工股份有限公司'},
     {'Status': '存续', 'FundedRatio': '9.9472%', 'ShouldCapi': '3471.65万元人民币', 'ShouldDate': 959184000,
      'ProvinceName': '河北', 'Industry': '制造业', 'ProductName': '-', 'StockName': '邯郸发达纺织印染有限责任公司'},
     {'Status': '存续', 'FundedRatio': '17.2414%', 'ShouldCapi': '3333.3333万元人民币', 'ShouldDate': 1469116800,
      'ProvinceName': '吉林', 'Industry': '制造业', 'ProductName': '-', 'StockName': '临江大华铸造股份有限公司'},
     {'Status': '在业', 'FundedRatio': '8.3665%', 'ShouldCapi': '3211.24万元人民币', 'ShouldDate': 0, 'ProvinceName': '陕西',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '西北二棉纺织有限公司'},
     {'Status': '存续', 'FundedRatio': '36.2085%', 'ShouldCapi': '3203万元人民币', 'ShouldDate': 1368460800,
      'ProvinceName': '黑龙江', 'Industry': '制造业', 'ProductName': '首泉农业', 'StockName': '哈尔滨首泉农业设备股份有限公司'},
     {'Status': '存续', 'FundedRatio': '15.1204%', 'ShouldCapi': '3028.369658万元人民币', 'ShouldDate': 1640880000,
      'ProvinceName': '新疆', 'Industry': '建筑业', 'ProductName': '-', 'StockName': '新疆生产建设兵团交通建设有限公司'},
     {'Status': '存续', 'FundedRatio': '5.717%', 'ShouldCapi': '3017.9731万元人民币', 'ShouldDate': 1022860800,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '北台铸管', 'StockName': '本溪北台铸管股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.865%', 'ShouldCapi': '2741.42万元人民币', 'ShouldDate': 979747200,
      'ProvinceName': '江西', 'Industry': '制造业', 'ProductName': '晶昊盐化', 'StockName': '江西晶昊盐化有限公司'},
     {'Status': '存续', 'FundedRatio': '6.654%', 'ShouldCapi': '2739.95万元人民币', 'ShouldDate': 996163200,
      'ProvinceName': '新疆', 'Industry': '制造业', 'ProductName': '八棉纺织', 'StockName': '新疆石河子八棉纺织有限公司'},
     {'Status': '存续', 'FundedRatio': '90%', 'ShouldCapi': '2700万元人民币', 'ShouldDate': 1161014400, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '中润经济发展有限责任公司'},
     {'Status': '存续', 'FundedRatio': '7.3396%', 'ShouldCapi': '2600万元人民币', 'ShouldDate': 1054828800,
      'ProvinceName': '新疆', 'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '-', 'StockName': '新疆天山电力股份有限公司'},
     {'Status': '存续', 'FundedRatio': '96.1832%', 'ShouldCapi': '2520万元人民币', 'ShouldDate': 1750780800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信莆悦投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '20%', 'ShouldCapi': '2461.54万元人民币', 'ShouldDate': 1213027200,
      'ProvinceName': '广东', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '中广核产业投资基金管理有限公司'},
     {'Status': '在业', 'FundedRatio': '9.84%', 'ShouldCapi': '2460万元人民币', 'ShouldDate': 1325174400, 'ProvinceName': '陕西',
      'Industry': '采矿业', 'ProductName': '五洲矿业', 'StockName': '陕西五洲矿业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '14.61%', 'ShouldCapi': '24,000,000股', 'ShouldDate': 0, 'ProvinceName': '四川',
      'Industry': '建筑业', 'ProductName': '中川国际', 'StockName': '中国四川国际合作股份有限公司'},
     {'Status': '存续', 'FundedRatio': '6.52%', 'ShouldCapi': '24,000,000股', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '制造业', 'ProductName': '杰事杰', 'StockName': '合肥杰事杰新材料股份有限公司'},
     {'Status': '存续', 'FundedRatio': '4.4364%', 'ShouldCapi': '2346.69万元人民币', 'ShouldDate': 997286400,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '南阳金冠集团有限责任公司'},
     {'Status': '存续', 'FundedRatio': '13.21%', 'ShouldCapi': '22,800,000股', 'ShouldDate': 0, 'ProvinceName': '湖北',
      'Industry': '农、林、牧、渔业', 'ProductName': '金旭农发', 'StockName': '湖北金旭农业发展股份有限公司'},
     {'Status': '存续', 'FundedRatio': '40%', 'ShouldCapi': '2000万元人民币', 'ShouldDate': 988387200, 'ProvinceName': '辽宁',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '青岛啤酒（鞍山）有限公司'},
     {'Status': '存续', 'FundedRatio': '14.3527%', 'ShouldCapi': '1849.2万元人民币', 'ShouldDate': 996508800,
      'ProvinceName': '湖南', 'Industry': '批发和零售业', 'ProductName': '飞碟新材料', 'StockName': '湖南飞碟新材料有限责任公司'},
     {'Status': '存续', 'FundedRatio': '34.36%', 'ShouldCapi': '1779.85万元人民币', 'ShouldDate': 1218988800,
      'ProvinceName': '安徽', 'Industry': '住宿和餐饮业', 'ProductName': '-', 'StockName': '安徽饭店'},
     {'Status': '存续', 'FundedRatio': '43.75%', 'ShouldCapi': '1776.25万元人民币', 'ShouldDate': 1914422400,
      'ProvinceName': '天津', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '信乐金惠（天津）投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '29%', 'ShouldCapi': '1740万元人民币', 'ShouldDate': 990720000, 'ProvinceName': '海南',
      'Industry': '文化、体育和娱乐业', 'ProductName': '-', 'StockName': '海南博鳌高尔夫有限公司'},
     {'Status': '存续', 'FundedRatio': '12.9432%', 'ShouldCapi': '1708.5022万元人民币', 'ShouldDate': 1251388800,
      'ProvinceName': '湖南', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '湖南永利化工股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.5179%', 'ShouldCapi': '1655.8972万元人民币', 'ShouldDate': 1385395200,
      'ProvinceName': '云南', 'Industry': '制造业', 'ProductName': '云南煤化', 'StockName': '云南煤化工集团有限公司'},
     {'Status': '在业', 'FundedRatio': '1.52%', 'ShouldCapi': '16,500,000股', 'ShouldDate': 0, 'ProvinceName': '陕西',
      'Industry': '制造业', 'ProductName': '达尔曼', 'StockName': '西安达尔曼实业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '10.0967%', 'ShouldCapi': '1639万元人民币', 'ShouldDate': 1012492800,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '-', 'StockName': '沈阳气体压缩机股份有限公司'},
     {'Status': '存续', 'FundedRatio': '6%', 'ShouldCapi': '1500万元人民币', 'ShouldDate': 1323964800, 'ProvinceName': '云南',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '昆明邦信小额贷款有限责任公司'},
     {'Status': '存续', 'FundedRatio': '20%', 'ShouldCapi': '1400万元人民币', 'ShouldDate': 1464019200, 'ProvinceName': '北京',
      'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '中广电信有限公司'},
     {'Status': '存续', 'FundedRatio': '8.35%', 'ShouldCapi': '10,700,000股', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '制造业', 'ProductName': '晨泰科技', 'StockName': '浙江晨泰科技股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.4899%', 'ShouldCapi': '1040.48万元人民币', 'ShouldDate': 1411920000,
      'ProvinceName': '贵州', 'Industry': '批发和零售业', 'ProductName': '开磷集团', 'StockName': '贵州开磷集团股份有限公司'},
     {'Status': '存续', 'FundedRatio': '3.4178%', 'ShouldCapi': '1020万元人民币', 'ShouldDate': 1312128000,
      'ProvinceName': '河南', 'Industry': '采矿业', 'ProductName': '灵宝金源', 'StockName': '灵宝金源矿业股份有限公司'},
     {'Status': '存续', 'FundedRatio': '25%', 'ShouldCapi': '1000万元人民币', 'ShouldDate': 1002816000, 'ProvinceName': '黑龙江',
      'Industry': '信息传输、软件和信息技术服务业', 'ProductName': '-', 'StockName': '黑龙江巨恒航天科技发展股份有限公司'},
     {'Status': '存续', 'FundedRatio': '20%', 'ShouldCapi': '1000万元人民币', 'ShouldDate': 1693411200, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '马鞍山信安企业管理有限责任公司'},
     {'Status': '存续', 'FundedRatio': '16.4%', 'ShouldCapi': '820万元人民币', 'ShouldDate': 1422374400, 'ProvinceName': '辽宁',
      'Industry': '采矿业', 'ProductName': '沈北煤矿', 'StockName': '沈阳沈北煤矿有限公司'},
     {'Status': '存续', 'FundedRatio': '9%', 'ShouldCapi': '117万美元', 'ShouldDate': 849542400, 'ProvinceName': '上海',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '上海海欣化纤有限公司'},
     {'Status': '存续', 'FundedRatio': '1.8582%', 'ShouldCapi': '692.2012万元人民币', 'ShouldDate': 1609084800,
      'ProvinceName': '湖北', 'Industry': '科学研究和技术服务业', 'ProductName': '安翰科技', 'StockName': '安翰科技（武汉）股份有限公司'},
     {'Status': '存续', 'FundedRatio': '6.847%', 'ShouldCapi': '684.7万元人民币', 'ShouldDate': 1293724800,
      'ProvinceName': '甘肃', 'Industry': '租赁和商务服务业', 'ProductName': 'BNMC', 'StockName': '白银有色产业集团有限责任公司'},
     {'Status': '存续', 'FundedRatio': '1.5267%', 'ShouldCapi': '675.6467万元人民币', 'ShouldDate': 1596556800,
      'ProvinceName': '湖北', 'Industry': '交通运输、仓储和邮政业', 'ProductName': '翼达建服', 'StockName': '武汉翼达建设服务股份有限公司'},
     {'Status': '在业', 'FundedRatio': '2.3612%', 'ShouldCapi': '660.264万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '制造业', 'ProductName': '东阳光药业', 'StockName': '广东东阳光药业有限公司'},
     {'Status': '存续', 'FundedRatio': '1.82%', 'ShouldCapi': '7,293,040股', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '批发和零售业', 'ProductName': '金田实业', 'StockName': '金田实业（集团）股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.6056%', 'ShouldCapi': '605.6万元人民币', 'ShouldDate': 1185552000,
      'ProvinceName': '辽宁', 'Industry': '制造业', 'ProductName': '大连机床', 'StockName': '大连机床（数控）股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.4655%', 'ShouldCapi': '592.5304万元人民币', 'ShouldDate': 1549036800,
      'ProvinceName': '江苏', 'Industry': '批发和零售业', 'ProductName': '苏纺集团', 'StockName': '江苏苏豪纺织集团有限公司'},
     {'Status': '存续', 'FundedRatio': '2.9772%', 'ShouldCapi': '510万元人民币', 'ShouldDate': 1603987200,
      'ProvinceName': '新疆', 'Industry': '金融业', 'ProductName': '-', 'StockName': '石河子国民村镇银行有限责任公司'},
     {'Status': '存续', 'FundedRatio': '0.424%', 'ShouldCapi': '504.167194万元人民币', 'ShouldDate': 1364659200,
      'ProvinceName': '江苏', 'Industry': '制造业', 'ProductName': 'WSP控股', 'StockName': '无锡西姆莱斯石油专用管制造有限公司'},
     {'Status': '存续', 'FundedRatio': '2.4409%', 'ShouldCapi': '482万元人民币', 'ShouldDate': 994176000, 'ProvinceName': '江西',
      'Industry': '制造业', 'ProductName': '景光电子', 'StockName': '江西景光电子有限公司'},
     {'Status': '存续', 'FundedRatio': '1.4297%', 'ShouldCapi': '457.504万元人民币', 'ShouldDate': 1648137600,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '双瑞特装', 'StockName': '中船双瑞（洛阳）特种装备股份有限公司'},
     {'Status': '存续', 'FundedRatio': '80%', 'ShouldCapi': '400万元人民币', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖沁嘉股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '6.06%', 'ShouldCapi': '4,000,000股', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '信息传输、软件和信息技术服务业', 'ProductName': '考拉超课', 'StockName': '深圳市考拉超课科技股份有限公司'},
     {'Status': '存续', 'FundedRatio': '0.5721%', 'ShouldCapi': '343.2592万元人民币', 'ShouldDate': 0, 'ProvinceName': '云南',
      'Industry': '采矿业', 'ProductName': '东源煤业', 'StockName': '云南东源煤业集团有限公司'},
     {'Status': '存续', 'FundedRatio': '100%', 'ShouldCapi': '300万元人民币', 'ShouldDate': 0, 'ProvinceName': '辽宁',
      'Industry': '住宿和餐饮业', 'ProductName': '-', 'StockName': '鞍山市金龙大厦'},
     {'Status': '存续', 'FundedRatio': '0.9999%', 'ShouldCapi': '200万元人民币', 'ShouldDate': 1301500800,
      'ProvinceName': '吉林', 'Industry': '建筑业', 'ProductName': '-', 'StockName': '吉林市第一建筑工程股份有限公司'},
     {'Status': '存续', 'FundedRatio': '2.2727%', 'ShouldCapi': '200万元人民币', 'ShouldDate': 1150646400,
      'ProvinceName': '北京', 'Industry': '科学研究和技术服务业', 'ProductName': '-', 'StockName': '北京德恒有限责任公司'},
     {'Status': '存续', 'FundedRatio': '0.919%', 'ShouldCapi': '135万元人民币', 'ShouldDate': 993571200, 'ProvinceName': '江西',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '江西景华电子有限责任公司'},
     {'Status': '存续', 'FundedRatio': '12%', 'ShouldCapi': '60万元人民币', 'ShouldDate': 1081094400, 'ProvinceName': '北京',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '北京金网络置业投资顾问有限公司'},
     {'Status': '存续', 'FundedRatio': '0.2893%', 'ShouldCapi': '19.095万元人民币', 'ShouldDate': 1348156800,
      'ProvinceName': '湖南', 'Industry': '农、林、牧、渔业', 'ProductName': '天心种业', 'StockName': '湖南天心种业有限公司'},
     {'Status': '存续', 'FundedRatio': '0.2281%', 'ShouldCapi': '11.402638万元人民币', 'ShouldDate': 1559232000,
      'ProvinceName': '浙江', 'Industry': '水利、环境和公共设施管理业', 'ProductName': '-', 'StockName': '绍兴市柯桥区鲁镇旅游发展有限公司'},
     {'Status': '在业', 'FundedRatio': '100%', 'ShouldCapi': '10万元人民币', 'ShouldDate': 1392998400, 'ProvinceName': '广东',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '珠海市宝盈北信投资咨询有限公司'},
     {'Status': '存续', 'FundedRatio': '0.2281%', 'ShouldCapi': '8.5974万元人民币', 'ShouldDate': 1544889600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '浙江柯岩风景区开发股份有限公司'},
     {'Status': '仍注册', 'FundedRatio': '100%', 'ShouldCapi': '24,689,500,000股', 'ShouldDate': 0, 'ProvinceName': '中国香港',
      'Industry': '-', 'ProductName': '-', 'StockName': '中國信達（香港）控股有限公司'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信石信锦股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南京信城投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '浙江浙能绿色能源股权投资基金合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖沁欣股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖信石华油投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '扬州芯贸创业投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '67.9802%', 'ShouldCapi': '53480', 'ShouldDate': 1812988800, 'ProvinceName': '天津',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '天津信首津投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '苏州国丰鼎信创业投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '99.6205%', 'ShouldCapi': '26250', 'ShouldDate': 1822233600, 'ProvinceName': '山东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '淄博盈科值得六号股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南京信璟纾困产业投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '99.5455%', 'ShouldCapi': '10950', 'ShouldDate': 1751644800, 'ProvinceName': '天津',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '天津信安投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南京珑胤信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '23000万元人民币', 'ShouldDate': 1817395200, 'ProvinceName': '安徽',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信熙投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖武信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖广交汇展投资合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '苏州市创新产业发展引导基金（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '湖北', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '湖北嘉桐盛私募基金合伙企业（有限合伙）'},
     {'Status': '在业', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '广东', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '珠海横琴穗信玟泰投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖信思达投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南通信达中金接续股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖沁雅股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南京信发能股权投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖源明信投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '江苏信鸿投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖如意信博投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '信达法拍（江苏）创新投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '苏州璞华致荣创业投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '南京信创投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖同汇投资合伙企业（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '安徽', 'Industry': '金融业',
      'ProductName': '-', 'StockName': '芜湖信愉达恒投资中心（有限合伙）'},
     {'Status': '存续', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '江苏',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '镇江交产结构调整资产投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '10.9906%', 'ShouldCapi': '33549.8559万元人民币', 'ShouldDate': 792950400,
      'ProvinceName': '青海', 'Industry': '批发和零售业', 'ProductName': '盐湖集团', 'StockName': '青海盐湖工业集团股份有限公司'},
     {'Status': '注销', 'FundedRatio': '57.4444%', 'ShouldCapi': '1350000万元人民币', 'ShouldDate': 1510243200,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖卓安投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '49.9955%', 'ShouldCapi': '550000万元人民币', 'ShouldDate': 1455811200,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳市鼎信丰投资发展合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '47.7725%', 'ShouldCapi': '430000万元人民币', 'ShouldDate': 1441728000,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳市信瑞丰投资发展合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '83.9832%', 'ShouldCapi': '420000万元人民币', 'ShouldDate': 1480521600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区融信博金投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '79.4661%', 'ShouldCapi': '387000万元人民币', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖君信胜达投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '91.7317%', 'ShouldCapi': '370000万元人民币', 'ShouldDate': 1468944000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信东圳投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '78.9321%', 'ShouldCapi': '354792万元人民币', 'ShouldDate': 0, 'ProvinceName': '甘肃',
      'Industry': '采矿业', 'ProductName': '-', 'StockName': '白银有色金属（集团）有限责任公司'},
     {'Status': '注销', 'FundedRatio': '99.9627%', 'ShouldCapi': '268000万元人民币', 'ShouldDate': 1476720000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信善投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '79.9667%', 'ShouldCapi': '239900万元人民币', 'ShouldDate': 1595692800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信晋阳投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '83.2986%', 'ShouldCapi': '200000万元人民币', 'ShouldDate': 1472572800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信深龙门投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '68.9417%', 'ShouldCapi': '200000万元人民币', 'ShouldDate': 1488816000,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信正希望投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '15.9521%', 'ShouldCapi': '166250万元人民币', 'ShouldDate': 997891200,
      'ProvinceName': '湖北', 'Industry': '制造业', 'ProductName': '-', 'StockName': '武汉钢铁有限责任公司'},
     {'Status': '注销', 'FundedRatio': '49.9825%', 'ShouldCapi': '142500万元人民币', 'ShouldDate': 1463673600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区华实投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '69.9301%', 'ShouldCapi': '140000万元人民币', 'ShouldDate': 1735056000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区绿信城达投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '82.391%', 'ShouldCapi': '139900万元人民币', 'ShouldDate': 1471276800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信文投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '74.9432%', 'ShouldCapi': '131900万元人民币', 'ShouldDate': 1494259200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区东信旭新能源投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '37.6522%', 'ShouldCapi': '129900万元人民币', 'ShouldDate': 1482076800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信豫康投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '62.4844%', 'ShouldCapi': '125000万元人民币', 'ShouldDate': 1445443200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波聚信喜兆投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.9167%', 'ShouldCapi': '120000万元人民币', 'ShouldDate': 1427299200,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '宁波正中信投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '92.2308%', 'ShouldCapi': '119900万元人民币', 'ShouldDate': 1544630400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区万房家隆投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.8335%', 'ShouldCapi': '119900万元人民币', 'ShouldDate': 1433779200,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳信岭圆熙基金管理企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '49.9783%', 'ShouldCapi': '115000万元人民币', 'ShouldDate': 1454342400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波佳源投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.99%', 'ShouldCapi': '99990万元人民币', 'ShouldDate': 1482422400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信新投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.9%', 'ShouldCapi': '99900万元人民币', 'ShouldDate': 1465920000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区福晟钱隆樽品投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '33.3218%', 'ShouldCapi': '96000万元人民币', 'ShouldDate': 1418832000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波中投建邦转山投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '43.2063%', 'ShouldCapi': '87738.2万元人民币', 'ShouldDate': 1161705600,
      'ProvinceName': '贵州', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '贵州水城煤电有限责任公司'},
     {'Status': '注销', 'FundedRatio': '79.9239%', 'ShouldCapi': '84000万元人民币', 'ShouldDate': 1490112000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区金楠投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '55.6933%', 'ShouldCapi': '83540万元人民币', 'ShouldDate': 1462723200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信戊投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '79.9%', 'ShouldCapi': '79900万元人民币', 'ShouldDate': 1469030400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信骋投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '72.738%', 'ShouldCapi': '61900万元人民币', 'ShouldDate': 1546185600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波市信泽瑞投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '19.4865%', 'ShouldCapi': '55659.5万元人民币', 'ShouldDate': 0, 'ProvinceName': '辽宁',
      'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '沈阳矿业有限责任公司'},
     {'Status': '注销', 'FundedRatio': '48.9051%', 'ShouldCapi': '51546万元人民币', 'ShouldDate': 1510761600,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳盘江壹号投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '17.8508%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1437667200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波宝能信投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '31.2305%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1609084800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '嘉兴信铜投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '83.1947%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1521993600,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信巴新能源投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '4.9995%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1480262400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区达悦颐合投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '4.9995%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1465315200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区人保信达投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '9.998%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1408982400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波春熙投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '24.9875%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1449676800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波南瑞新能源投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.94%', 'ShouldCapi': '50000万元人民币', 'ShouldDate': 1437667200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信泽凯投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '6.3658%', 'ShouldCapi': '48977万元人民币', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '北京首钢新钢有限责任公司'},
     {'Status': '注销', 'FundedRatio': '2.6327%', 'ShouldCapi': '42600万元人民币', 'ShouldDate': 1602172800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波秋实投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '48.1379%', 'ShouldCapi': '41329.55万元人民币', 'ShouldDate': 989769600,
      'ProvinceName': '河北', 'Industry': '制造业', 'ProductName': '-', 'StockName': '秦皇岛耀华国投浮法玻璃有限责任公司'},
     {'Status': '注销', 'FundedRatio': '12.5%', 'ShouldCapi': '40000万元人民币', 'ShouldDate': 1571155200,
      'ProvinceName': '上海', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '上海文广投资管理中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '39.976%', 'ShouldCapi': '40000万元人民币', 'ShouldDate': 1417104000,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '宁波鑫凤投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.7143%', 'ShouldCapi': '34900万元人民币', 'ShouldDate': 1459267200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波天信风华投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '75.1054%', 'ShouldCapi': '34900万元人民币', 'ShouldDate': 1449676800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信达丝绸之路投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '62.4875%', 'ShouldCapi': '32800万元人民币', 'ShouldDate': 1427299200,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳市信达金海鸿业合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '8.569%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1407168000,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '宁波国寿信达投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '37.4532%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1470931200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信达邦泰投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '5.9988%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1369238400,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波春鸿投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '5.9988%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1380384000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波夏鼎投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '2.4388%', 'ShouldCapi': '30000万元人民币', 'ShouldDate': 1411920000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波聚信通达投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '92.1418%', 'ShouldCapi': '29900万元人民币', 'ShouldDate': 1470672000,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信盛投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '3.415%', 'ShouldCapi': '26710万元人民币', 'ShouldDate': 1041264000,
      'ProvinceName': '河南', 'Industry': '采矿业', 'ProductName': '-', 'StockName': '平顶山煤业（集团）有限责任公司'},
     {'Status': '注销', 'FundedRatio': '11.2745%', 'ShouldCapi': '25310.32万元人民币', 'ShouldDate': 838569600,
      'ProvinceName': '青海', 'Industry': '制造业', 'ProductName': '-', 'StockName': '青海盐湖工业（集团）有限公司'},
     {'Status': '注销', 'FundedRatio': '19.9995%', 'ShouldCapi': '25000万元人民币', 'ShouldDate': 1365609600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '台州市绿泰投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '62.4975%', 'ShouldCapi': '24999万元人民币', 'ShouldDate': 1466092800,
      'ProvinceName': '安徽', 'Industry': '金融业', 'ProductName': '-', 'StockName': '芜湖信鑫一期股权投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '31.2438%', 'ShouldCapi': '24995万元人民币', 'ShouldDate': 1418659200,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波聚信颐和投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '74.7483%', 'ShouldCapi': '22500万元人民币', 'ShouldDate': 1482336000,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信达懿信投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '22.2198%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1482076800,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区兴冀龙奥投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '28.5694%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1378915200,
      'ProvinceName': '甘肃', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '甘肃宏达濬源投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '99.5025%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1505750400,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖朴益投资管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '39.9976%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1368633600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '台州市信泽建投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '13.7931%', 'ShouldCapi': '20000万元人民币', 'ShouldDate': 1513267200,
      'ProvinceName': '北京', 'Industry': '房地产业', 'ProductName': '京西潭柘', 'StockName': '北京京西潭柘投资发展控股有限公司'},
     {'Status': '注销', 'FundedRatio': '48.7555%', 'ShouldCapi': '19941万元人民币', 'ShouldDate': 1510761600,
      'ProvinceName': '广东', 'Industry': '金融业', 'ProductName': '-', 'StockName': '深圳盘江贰号投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '35.8%', 'ShouldCapi': '17900万元人民币', 'ShouldDate': 1461513600,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信达德商投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '10.8348%', 'ShouldCapi': '16600万元人民币', 'ShouldDate': 1372176000,
      'ProvinceName': '浙江', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波信安达投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '74.9251%', 'ShouldCapi': '15000万元人民币', 'ShouldDate': 1425830400,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '宁波信东壹期股权投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '49.995%', 'ShouldCapi': '15000万元人民币', 'ShouldDate': 1356624000,
      'ProvinceName': '四川', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '成都信达创富投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '25.1858%', 'ShouldCapi': '14484.9万元人民币', 'ShouldDate': 0, 'ProvinceName': '甘肃',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '兰州炭素集团有限责任公司'},
     {'Status': '注销', 'FundedRatio': '4.7719%', 'ShouldCapi': '12645万元人民币', 'ShouldDate': 0, 'ProvinceName': '山西',
      'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '山西潞安煤炭工业有限责任公司'},
     {'Status': '注销', 'FundedRatio': '44.7022%', 'ShouldCapi': '11522万元人民币', 'ShouldDate': 1083081600,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '平顶山星峰集团有限责任公司'},
     {'Status': '注销', 'FundedRatio': '20.1128%', 'ShouldCapi': '9700万元人民币', 'ShouldDate': 0, 'ProvinceName': '云南',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '云南沾化有限责任公司'},
     {'Status': '注销', 'FundedRatio': '25.694%', 'ShouldCapi': '15068万元人民币', 'ShouldDate': 1009209600,
      'ProvinceName': '河北', 'Industry': '制造业', 'ProductName': '-', 'StockName': '河北长芦黄骅盐业有限公司'},
     {'Status': '注销', 'FundedRatio': '46.7263%', 'ShouldCapi': '8878万元人民币', 'ShouldDate': 979747200,
      'ProvinceName': '重庆', 'Industry': '制造业', 'ProductName': '-', 'StockName': '重庆海康实业有限责任公司'},
     {'Status': '注销', 'FundedRatio': '31.4972%', 'ShouldCapi': '6591.86万元人民币', 'ShouldDate': 991324800,
      'ProvinceName': '甘肃', 'Industry': '制造业', 'ProductName': '-', 'StockName': '兰州红古祁连山水泥股份有限公司'},
     {'Status': '注销', 'FundedRatio': '22.9984%', 'ShouldCapi': '6400万元人民币', 'ShouldDate': 1345392000,
      'ProvinceName': '新疆', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '新疆博斯腾湖苇业（集团）有限责任公司'},
     {'Status': '注销', 'FundedRatio': '6.7104%', 'ShouldCapi': '5580万元人民币', 'ShouldDate': 1019836800,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '洛阳轴承集团有限公司'},
     {'Status': '注销', 'FundedRatio': '2.4988%', 'ShouldCapi': '5000万元人民币', 'ShouldDate': 1382976000,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '宁波信盈信股权投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '37.3448%', 'ShouldCapi': '4845万元人民币', 'ShouldDate': 0, 'ProvinceName': '湖南',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '长沙锌业有限责任公司'},
     {'Status': '注销', 'FundedRatio': '19.999%', 'ShouldCapi': '4000万元人民币', 'ShouldDate': 1466956800,
      'ProvinceName': '浙江', 'Industry': '金融业', 'ProductName': '-', 'StockName': '浙江镇远股权投资基金管理合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '2.3988%', 'ShouldCapi': '3682万元人民币', 'ShouldDate': 0, 'ProvinceName': '湖北',
      'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '-', 'StockName': '中国葛洲坝水利水电工程集团有限公司'},
     {'Status': '注销', 'FundedRatio': '2.6071%', 'ShouldCapi': '3426万元人民币', 'ShouldDate': 1011369600,
      'ProvinceName': '安徽', 'Industry': '制造业', 'ProductName': '-', 'StockName': '合肥新钢铁有限责任公司'},
     {'Status': '注销', 'FundedRatio': '5.5698%', 'ShouldCapi': '1750万元人民币', 'ShouldDate': 0, 'ProvinceName': '湖南',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '湘潭电机投资有限公司'},
     {'Status': '注销', 'FundedRatio': '0.7587%', 'ShouldCapi': '1373万元人民币', 'ShouldDate': 0, 'ProvinceName': '山东',
      'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '山东新岳能源有限责任公司'},
     {'Status': '注销', 'FundedRatio': '9.301%', 'ShouldCapi': '891.5万元人民币', 'ShouldDate': 0, 'ProvinceName': '辽宁',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '辽宁庆阳化工（集团）有限公司'},
     {'Status': '注销', 'FundedRatio': '45%', 'ShouldCapi': '450万元人民币', 'ShouldDate': 1369324800, 'ProvinceName': '河北',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '石家庄通旭投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '1.3606%', 'ShouldCapi': '401.8万元人民币', 'ShouldDate': 1155744000,
      'ProvinceName': '安徽', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '合肥钢铁股份有限公司'},
     {'Status': '注销', 'FundedRatio': '29.2994%', 'ShouldCapi': '330.497万元人民币', 'ShouldDate': 740592000,
      'ProvinceName': '浙江', 'Industry': '房地产业', 'ProductName': '-', 'StockName': '宁波广厦住房股份有限公司'},
     {'Status': '注销', 'FundedRatio': '10.4222%', 'ShouldCapi': '281.4万元人民币', 'ShouldDate': 1066147200,
      'ProvinceName': '广东', 'Industry': '制造业', 'ProductName': '-', 'StockName': '广州凯迪自行车工业有限公司'},
     {'Status': '注销', 'FundedRatio': '99.0774%', 'ShouldCapi': '107.39万元人民币', 'ShouldDate': 1449676800,
      'ProvinceName': '安徽', 'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖信达新长安投资合伙企业（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '100%', 'ShouldCapi': '100万元人民币', 'ShouldDate': 0, 'ProvinceName': '北京',
      'Industry': '住宿和餐饮业', 'ProductName': '-', 'StockName': '北京绿茵山庄'},
     {'Status': '注销', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '北京', 'Industry': '批发和零售业',
      'ProductName': '中材股份', 'StockName': '中国中材股份有限公司'},
     {'Status': '注销', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '湖南', 'Industry': '制造业',
      'ProductName': '-', 'StockName': '湖南浦沅工程机械有限责任公司'},
     {'Status': '注销', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '黑龙江', 'Industry': '采矿业',
      'ProductName': '-', 'StockName': '鹤岗煤矿集团有限公司'},
     {'Status': '注销', 'FundedRatio': '64.8148%', 'ShouldCapi': '10500', 'ShouldDate': 0, 'ProvinceName': '安徽',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '芜湖瑞可馨投资中心（有限合伙）'},
     {'Status': '注销', 'FundedRatio': '69.986%', 'ShouldCapi': '350000', 'ShouldDate': 0, 'ProvinceName': '浙江',
      'Industry': '租赁和商务服务业', 'ProductName': '-', 'StockName': '宁波梅山保税港区信仲夏投资合伙企业（有限合伙）'},
     {'Status': '吊销', 'FundedRatio': '37.393%', 'ShouldCapi': '78770万元人民币', 'ShouldDate': 990115200,
      'ProvinceName': '甘肃', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '酒钢集团甘肃宏信钢铁有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '61.4554%', 'ShouldCapi': '49946万元人民币', 'ShouldDate': 0, 'ProvinceName': '四川',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '四川省聚酯股份有限公司'},
     {'Status': '吊销', 'FundedRatio': '44.9664%', 'ShouldCapi': '47549.09万元人民币', 'ShouldDate': 0, 'ProvinceName': '内蒙古',
      'Industry': '采矿业', 'ProductName': '-', 'StockName': '赤峰平庄能源有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '28.2927%', 'ShouldCapi': '5988.39万元人民币', 'ShouldDate': 978192000,
      'ProvinceName': '安徽', 'Industry': '制造业', 'ProductName': '-', 'StockName': '安徽巢湖新元机械集团有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '16.8667%', 'ShouldCapi': '4061万元人民币', 'ShouldDate': 755107200,
      'ProvinceName': '河南', 'Industry': '制造业', 'ProductName': '-', 'StockName': '洛阳黄河水泥集团有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '9.2979%', 'ShouldCapi': '3409万元人民币', 'ShouldDate': 1034179200,
      'ProvinceName': '山东', 'Industry': '制造业', 'ProductName': '-', 'StockName': '山东东大化学工业有限公司'},
     {'Status': '吊销', 'FundedRatio': '5.8733%', 'ShouldCapi': '3106万元人民币', 'ShouldDate': 0, 'ProvinceName': '湖南',
      'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '湖南金信化工有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '27.57%', 'ShouldCapi': '3087.75万元人民币', 'ShouldDate': 0, 'ProvinceName': '江苏',
      'Industry': '制造业', 'ProductName': '耀荣玻璃', 'StockName': '南通耀荣玻璃股份有限公司'},
     {'Status': '吊销', 'FundedRatio': '43.5033%', 'ShouldCapi': '363.64万美元', 'ShouldDate': 1061740800,
      'ProvinceName': '辽宁', 'Industry': '房地产业', 'ProductName': '-', 'StockName': '信达飞宝（鞍山）房地产实业有限公司'},
     {'Status': '吊销', 'FundedRatio': '3.194%', 'ShouldCapi': '1263.24万元人民币', 'ShouldDate': 1093536000,
      'ProvinceName': '福建', 'Industry': '制造业', 'ProductName': '-', 'StockName': '福建省龙岩造纸有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '4.4986%', 'ShouldCapi': '1123万元人民币', 'ShouldDate': 1009468800,
      'ProvinceName': '安徽', 'Industry': '批发和零售业', 'ProductName': '-', 'StockName': '安徽宣城丝织集团有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '13.7922%', 'ShouldCapi': '1100万元人民币', 'ShouldDate': 840643200,
      'ProvinceName': '内蒙古', 'Industry': '电力、热力、燃气及水生产和供应业', 'ProductName': '-', 'StockName': '内蒙古风电能源有限责任公司'},
     {'Status': '吊销', 'FundedRatio': '0.1605%', 'ShouldCapi': '555万元人民币', 'ShouldDate': 0, 'ProvinceName': '广东',
      'Industry': '金融业', 'ProductName': '-', 'StockName': '南方证券股份有限公司'},
     {'Status': '吊销', 'FundedRatio': '12.5%', 'ShouldCapi': '500万元人民币', 'ShouldDate': 0, 'ProvinceName': '吉林',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '长春振兴实业股份有限公司'},
     {'Status': '吊销', 'FundedRatio': '75%', 'ShouldCapi': '65.787万美元', 'ShouldDate': 0, 'ProvinceName': '江苏',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '徐州天龙包装有限公司'},
     {'Status': '吊销', 'FundedRatio': '40%', 'ShouldCapi': '200万元人民币', 'ShouldDate': 0, 'ProvinceName': '吉林',
      'Industry': '房地产业', 'ProductName': '-', 'StockName': '白城市城市建设开发总公司'},
     {'Status': '吊销', 'FundedRatio': '', 'ShouldCapi': '', 'ShouldDate': 0, 'ProvinceName': '黑龙江', 'Industry': '批发和零售业',
      'ProductName': '-', 'StockName': '双鸭山双达煤业有限公司'},
     {'Status': '', 'FundedRatio': '2.9418%', 'ShouldCapi': '1030万元人民币', 'ShouldDate': 0, 'ProvinceName': '陕西',
      'Industry': '制造业', 'ProductName': '-', 'StockName': '西安冶金机械有限公司'}]


def GetStockName(item):
    NameList = []
    for k in item:
        StockName = k.get('StockName')
        NameList.append(StockName)
    return NameList


def GetKV(item):
    KV = []
    for l in item:
        str_k = ''
        str_v = ''
        for k, v in l.items():
            str_k += f"{k}" + ','
            str_v += f'"{v}"' + ','
        str_k += 'id'
        str_v += '1'
        print(str_k, str_v)


GetKV(s)
